# Generated by Django 4.2.3 on 2023-07-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workout_totalweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='focus',
            field=models.CharField(blank=True, choices=[('Push', 'Push'), ('Pull', 'Pull'), ('Leg', 'Leg')], max_length=50),
        ),
    ]
