# Generated by Django 4.2.3 on 2023-07-15 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workout_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('target', models.TextField(blank=True, choices=[('Shoulders', 'Shoulders'), ('Chest', 'Chest'), ('Quads', 'Quads'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps')])),
                ('repGoal', models.TextField(blank=True)),
                ('equipment', models.TextField(blank=True, choices=[('Free Weights', 'Free_Weights'), ('Machine', 'Machine'), ('Cable', 'Cable'), ('Bodyweight', 'Bodyweight')])),
                ('notes', models.TextField(blank=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workout')),
            ],
        ),
    ]
