# Generated by Django 4.2.3 on 2023-07-15 14:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.TextField(blank=True, choices=[('Free_Weights', 'Free Weights'), ('Machine', 'Machine'), ('Cable', 'Cable'), ('Bodyweight', 'Bodyweight')]),
        ),
        migrations.CreateModel(
            name='set',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('weight', models.FloatField(default=0.0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
            ],
        ),
    ]
