# Generated by Django 4.2.3 on 2023-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_exercise_equipment_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='reps',
            field=models.IntegerField(null=True),
        ),
    ]
